kind: Service
apiVersion: v1
metadata:
  name: password-api-service
  labels:
    app: password-api
spec:
  selector:
    app: password-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 4567
  type: NodePort